// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClaM065auQLqVZQCgRwf3u9DMqdD8yEIk',
    appId: '1:665761525967:web:99d888a13061494d4f07ba',
    messagingSenderId: '665761525967',
    projectId: 'newfitnessappbr',
    authDomain: 'newfitnessappbr.firebaseapp.com',
    storageBucket: 'newfitnessappbr.firebasestorage.app',
    measurementId: 'G-FZ2CQ5DGG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8qK9y1r3meU6TfuuPNACT9Si0xb2CsNk',
    appId: '1:665761525967:android:8562eba73c7be19b4f07ba',
    messagingSenderId: '665761525967',
    projectId: 'newfitnessappbr',
    storageBucket: 'newfitnessappbr.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUNG7dtWTeh_QdosrRMSF3y1f3evyvAYs',
    appId: '1:665761525967:ios:0ea252b48108edf14f07ba',
    messagingSenderId: '665761525967',
    projectId: 'newfitnessappbr',
    storageBucket: 'newfitnessappbr.firebasestorage.app',
    iosBundleId: 'com.newfitness.newfitness',
  );
}
